modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
# issueTrackerURL = "https://github.com/DakotaPride/thermal-numismatics/issues"

[[mods]]
modId = "thermalnumismatics"
version = "0.1.0"
displayName = "Thermal Numismatics"
# displayURL = "https://www.curseforge.com/minecraft/mc-mods/thermalnumismatics"
logoFile="thermalnumismatics.png"
credits = "Team CoFH"
authors = "DakotaPride"
description = '''
Port Trade Station from Create: Above & Beyond to 1.20.1

This is an unofficial Thermal Series mod, any issues relating to the Trade Station are most likely unrelated to the base Thermal Series/Foundation mods.
'''

[[dependencies.thermalnumismatics]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thermalnumismatics]]
modId = "cofh_core"
mandatory = true
versionRange = "${cofh_core_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermalnumismatics]]
modId = "thermal"
mandatory = true
versionRange = "${thermal_core_version_range}"
ordering = "AFTER"
side = "BOTH"